auth:
  username: ${USERNAME}
  password: ${PASSWORD}
  web_cookie: ${WEB_COOKIE}
  referer: "https://weibo.com/u/your_uid"

cookies:
  session_id: "your_session_id"
  csrf_token: "your_csrf_token"

headers:
  User-Agent: "your_user_agent"