name: Update Requirements

on:
#  push:
  pull_request:
    types: [opened, synchronize, reopened]
#    branches:
#      - main

permissions:
  contents: write

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs

      - name: Generate requirements.txt
        run: |
          rm -f requirements.txt
          pipreqs . --force

      - name: Check for changes
        id: git_diff
        run: |
          echo "checking git diff for changes"
          git diff --exit-code || echo "changed=true" >> $GITHUB_ENV

      - name: Commit and push requirements.txt
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
